### ISSUE TITLE
When does this clear cookies?

### ISSUE THREAD

**Issue by wefalltomorrow** [svandragt/freshcookies#6]
Does it clear the cookies on every browser startup or every few seconds/minutes/hours?

E.g. 
![image](https://user-images.githubusercontent.com/45746576/161719099-f6e56355-22f2-40ef-8cf7-48d052d7a986.png)

P.S. Would be great if the 30 day limit could be increased.

**Comment by svandragt** [comment]
Heya @wefalltomorrow.

> If a cookie has expired, the browser does not send that particular cookie to the server with the page request; instead, the expired cookie is deleted.

This addon does not change anything about the process of deleting expired cookies, it just changes the date when it expires.

Regarding increasing of the limit, how long would you like to set the max expiry date? And what's the reason for that? Thanks

**Comment by wefalltomorrow** [comment]
Thanks for the response, still learning how cookie expiration works :)

Well 60 would be a good general max expiry date, I like to use 45 days. Seems to be a good middle ground.
